name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "Foo" > foo.txt
      - run: |
          ls -al
      - run: |
          date
    
  call:
    uses: shimat/reusable_workflow_sample/.github/workflows/reusable.yml@main
    needs: [build]
    with:
      name: "Alice"
